Fix crash when alpha is None
```
MeerK40t crash log. Version: 0.7.0 RC-10 on win32
Traceback (most recent call last):
  File "meerk40t\gui\wxmeerk40t.py", line 3733, in specific
  File "meerk40t\core\elements.py", line 1570, in inner
  File "meerk40t\core\elements.py", line 4221, in refresh_clasifications
  File "meerk40t\core\elements.py", line 5216, in classify
AttributeError: 'NoneType' object has no attribute 'alpha'
```